version: '2'
services:
  app: &main
    build: .
    image: keboola/db-writer-pgsql
    working_dir: /code
    command: composer ci
    tty: true
    stdin_open: true
    environment:
      PGSQL_DB_HOST: pgsql
      PGSQL_DB_PORT: 5432
      PGSQL_DB_USER: postgres
      PGSQL_DB_PASSWORD: some password
      PGSQL_DB_DATABASE: postgres
      PGSQL_DB_SCHEMA: public
    depends_on:
      - pgsql
      - sshproxy

  dev:
    <<: *main
    image: keboola/db-writer-pgsql-dev
    volumes:
      - .:/code

  pgsql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: some password

  sshproxy:
    image: sshproxy-pgsql
    build: ./tests/docker/sshproxy
    volumes:
        - ./tests/docker/sshproxy:/code
    working_dir: /code
    ports:
      - "2222:22"
    links:
      - pgsql
